name: just_match
description: A naive pattern matching for Dart.
version: 0.0.1
repository: https://github.com/cn202k/dart_just_match.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: